rules:
  indentation:
    spaces: 2
  line-length:
    max: 100
  trailing-spaces:
    level: error
    
  required-fields:
    paths:
      "kubernetes/*.yaml":
        - apiVersion
        - kind
        - metadata.name
        
exclude:
  - "**/.git/"
  - "**/vendor/"
